@startuml
left to right direction

actor guest
actor student
actor teacher
actor dean

student <|-- teacher
teacher <|-- dean

package connection {
    (login)
    (logout)
}
student --> connection

package grades {
    (check grades)
    (add grades)
    (modify grades)
    (generate score sheet)
}
student --> (check grades)
teacher --> (add grades)
teacher --> (modify grades)
dean --> (generate score sheet)

note right of (check grades)
    A teacher can only check grades that he is teaching.
    He also can check student's grades.
end note

note right of (check grades)
    A student can only check his own grades.
end note

note right of (add grades)
    A teacher can only add grades that he is teaching.
end note

note right of (modify grades)
    A teacher can only modify grades that he is teaching.
end note

package examination {
    (add an examination)
    (modify an examination)
}
teacher --> (add an examination)
teacher --> (modify an examination)

note right of (add an examination)
    A teacher can only add examination that he is teaching.
end note

note right of (modify an examination)
    A teacher can only modify examination that he is teaching.
end note

package student_management {
    (create a student)
    (modify a student)
    (archive a student)
}
dean --> student_management

package teacher_management {
    (create a teacher)
    (modify a teacher)
    (archive a teacher)
}
dean --> teacher_management

package class_management {
    (create a class)
    (archive a class)
    (modify a class)
    (assign students to a class)
}
dean --> class_management

package course {
    (add a course)
    (modify a course)
    (archive a course)
    (add a teacher to a course)
}
dean --> course

@enduml
